// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjkincnvqnsytqixduvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqa2luY252cW5zeXRxaXhkdXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDMzODYsImV4cCI6MjA1NzY3OTM4Nn0.gGI-9DQ0Pc06iuVoQm0aLW_ZN398r5g6QkBDEvMErXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);